- name: Download Obsidian
  get_url:
    url: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.4.16/obsidian_1.4.16_amd64.deb
    dest: /tmp/obsidian.deb
  tags:
    - install
    - obsidian
- name: install obsidian .deb package
  become: true
  apt:
    deb: /tmp/obsidian.deb
  tags:
    - install
    - obsidian
