- name: Install packages "wireshark", "fzf",  "gimp", "xclip", "screenkey", "tldr", "ripgrep"
  become: true
  apt:
    name: [ "wireshark", "fzf",  "gimp", "xclip", "screenkey", "tldr", "ripgrep" ]
  tags:
    - install
    - productivity

